# Generated by Django 3.0.5 on 2020-06-05 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharebazaar_app', '0004_auto_20200606_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='buy_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Buy Price'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='sell_date',
            field=models.DateField(blank=True, null=True, verbose_name='Sold Date'),
        ),
    ]
